project_id = "rllgepvklxqyhegrqodw"

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-create-checkout]
verify_jwt = true

[functions.stripe-customer-portal] 
verify_jwt = true

[functions.get-stripe-subscription]
verify_jwt = true

[functions.check-grace-periods]
verify_jwt = false

[functions.debug-subscription]
verify_jwt = true

[functions.start-live-preview]
verify_jwt = true

[functions.fix-subscription-status]
verify_jwt = true

[functions.sync-subscription-status]
verify_jwt = true

[functions.handle-subscription-success]
verify_jwt = true

[functions.test-payment-flow]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false