project_id = "rllgepvklxqyhegrqodw"

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-create-checkout]
verify_jwt = true

[functions.stripe-customer-portal] 
verify_jwt = true

[functions.get-stripe-subscription]
verify_jwt = true

[functions.check-grace-periods]
verify_jwt = false

[functions.debug-subscription]
verify_jwt = true

[functions.fix-subscription-status]
verify_jwt = true